### ISSUE TITLE
it's can be used for API?

### ISSUE THREAD

**Issue by SHELA** [ivanomatteo/laravel-device-tracking#1]
Hello,
it's can be used for API?
since cookies/session on API it's oauth token

**Comment by ivanomatteo** [comment]
Session is not mandatory, it's used only by the middleware, if api are consumed by a browser, then it's possible to attach the identifier cookie.

In a oauth or token based scheme where the the client is not a browser, it's not possible to attach a device unique identifier, most of the information are in the token, that may contain trackable information, but since it's a **bearer** token, it's not strictly related to the device.
